name: ak
on:
    push:
     branches:
        - main


jobs:
    job-extract:
        runs-on: ubuntu-latest

        steps:
             - name: checkout code
               uses: actions/checkout@v2
            
             - name: run e.py
               run: python e.py
        
    job-transform:
        runs-on: ubuntu-latest

        steps: 
            - name: checkout code
              uses: actions/checkout@v2

            - name: run t.py
              run: python t.py
              
    job-load:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: run l.py
              run: python l.py
              